baseURL = "https://nicolezok.com"
enableEmoji = true
languageCode = "en-us"
publishDir = "public"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
theme = "hermit"
title = "website"
[author]
name = "Nicole Zok"
[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10
[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
